name: gallery_saver
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.0.2
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.youmtinetpacks.gallery_saver
        pluginClass: GallerySaverPlugin
      ios:
        pluginClass: GallerySaverPlugin
